(function() {
  if (!("text/x-latex" in CodeMirror.mimeModes))
    return;
  function latex_autocomplete() {
    var keywords = ["\\accurrent", "\\acidfree", "\\acute", "\\acwcirclearrow",
      "\\acwgapcirclearrow", "\\acwleftarcarrow", "\\acwopencirclearrow",
      "\\acwoverarcarrow", "\\acwunderarcarrow", "\\adots", "\\aleph",
      "\\alpha", "\\amalg", "\\angdnr", "\\angle", "\\angles", "\\angleubar",
      "\\Angstrom", "\\annuity", "\\APLboxquestion", "\\APLboxupcaret",
      "\\APLnotbackslash", "\\APLnotslash", "\\approx", "\\approxeq",
      "\\approxeqq", "\\approxident", "\\arabichad", "\\arabicmaj", "\\arccos",
      "\\arceq", "\\arcsin", "\\arctan", "\\arg", "\\argmax", "\\argmin",
      "\\assert", "\\ast", "\\asteq", "\\asteraccent", "\\astrosun", "\\asymp",
      "\\awint", "\\b", "\\backcong", "\\backdprime", "\\backprime",
      "\\backsim", "\\backsimeq", "\\backslash", "\\backtrprime",
      "\\bagmember", "\\bar", "\\barcap", "\\barcup", "\\bardownharpoonleft",
      "\\bardownharpoonright", "\\barleftarrow", "\\barleftarrowrightarrowbar",
      "\\barleftharpoondown", "\\barleftharpoonup", "\\barovernorthwestarrow",
      "\\barrightarrowdiamond", "\\barrightharpoondown", "\\barrightharpoonup",
      "\\baruparrow", "\\barupharpoonleft", "\\barupharpoonright", "\\Barv",
      "\\barV", "\\barvee", "\\barwedge", "\\BbbC", "\\Bbbeight", "\\Bbbfive",
      "\\Bbbfour", "\\BbbGamma", "\\Bbbgamma", "\\BbbH", "\\BbbN", "\\Bbbnine",
      "\\Bbbone", "\\BbbP", "\\BbbPi", "\\Bbbpi", "\\BbbQ", "\\BbbR",
      "\\Bbbseven", "\\Bbbsix", "\\Bbbsum", "\\Bbbthree", "\\Bbbtwo", "\\BbbZ",
      "\\Bbbzero", "\\bbrktbrk", "\\bdtriplevdash", "\\because",
      "\\begin{center}", "\\begin{description}", "\\begin{document}",
      "\\begin{enumerate}", "\\begin{itemize}", "\\begin{tabular}",
      "\\benzenr", "\\beta", "\\beth", "\\between", "\\bf",
      "\\bigblacktriangledown", "\\bigblacktriangleup", "\\bigbot", "\\bigcap",
      "\\bigcirc", "\\bigcup", "\\bigcupdot", "\\biginterleave", "\\bigodot",
      "\\bigoplus", "\\bigotimes", "\\bigskip", "\\bigslopedvee",
      "\\bigslopedwedge", "\\bigsqcap", "\\bigsqcup", "\\bigstar",
      "\\bigtalloblong", "\\bigtimes", "\\bigtop", "\\bigtriangledown",
      "\\bigtriangleleft", "\\bigtriangleup", "\\biguplus", "\\bigvee",
      "\\bigwedge", "\\bigwhitestar", "\\blackcircledownarrow",
      "\\blackcircledrightdot", "\\blackcircledtwodots",
      "\\blackcircleulquadwhite", "\\blackdiamonddownarrow",
      "\\blackhourglass", "\\blackinwhitediamond", "\\blackinwhitesquare",
      "\\blacklefthalfcircle", "\\blackpointerleft", "\\blackpointerright",
      "\\blackrighthalfcircle", "\\blacksmiley", "\\blacktriangle",
      "\\blacktriangledown", "\\blacktriangleleft", "\\blacktriangleright",
      "\\blanksymbol", "\\blkhorzoval", "\\blkvertoval", "\\blockfull",
      "\\blockhalfshaded", "\\blocklefthalf", "\\blocklowhalf",
      "\\blockqtrshaded", "\\blockrighthalf", "\\blockthreeqtrshaded",
      "\\blockuphalf", "\\bmod", "\\bNot", "\\bot", "\\botsemicircle",
      "\\bowtie", "\\Box", "\\boxast", "\\boxbar", "\\boxbox", "\\boxbslash",
      "\\boxcircle", "\\boxdiag", "\\boxdot", "\\boxminus", "\\boxonbox",
      "\\boxplus", "\\boxtimes", "\\breve", "\\bsimilarleftarrow",
      "\\bsimilarrightarrow", "\\bsolhsub", "\\btimes", "\\bullet",
      "\\bullseye", "\\Bumpeq", "\\bumpeq", "\\bumpeqq", "\\c", "\\candra",
      "\\Cap", "\\cap", "\\capbarcup", "\\capdot", "\\capovercup",
      "\\capwedge", "\\caretinsert", "\\carriagereturn",
      "\\ccwundercurvearrow", "\\cdot", "\\cdotp", "\\cdots", "\\chapter",
      "\\check", "\\checkmark", "\\chi", "\\cirbot", "\\circ", "\\circeq",
      "\\circlebottomhalfblack", "\\circledast", "\\circledbullet",
      "\\circledcirc", "\\circleddash", "\\circledequal", "\\circledownarrow",
      "\\circledparallel", "\\circledrightdot", "\\circledstar",
      "\\circledtwodots", "\\circledvert", "\\circledwhitebullet",
      "\\circlehbar", "\\circlelefthalfblack", "\\circlellquad",
      "\\circlelrquad", "\\circleonleftarrow", "\\circleonrightarrow",
      "\\circlerighthalfblack", "\\circletophalfblack", "\\circleulquad",
      "\\circleurquad", "\\circleurquadblack", "\\circlevertfill", "\\cirE",
      "\\cirfnint", "\\cirmid", "\\cirscir", "\\cite", "\\clearpage",
      "\\closedvarcap", "\\closedvarcup", "\\closedvarcupsmashprod",
      "\\closure", "\\clubsuit", "\\Colon", "\\Coloneq", "\\coloneq",
      "\\commaminus", "\\complement", "\\concavediamond",
      "\\concavediamondtickleft", "\\concavediamondtickright", "\\cong",
      "\\congdot", "\\conictaper", "\\conjquant", "\\coprod", "\\cos",
      "\\cosh", "\\cot", "\\coth", "\\csc", "\\csub", "\\csube", "\\csup",
      "\\csupe", "\\cuberoot", "\\Cup", "\\cup", "\\cupbarcap", "\\cupdot",
      "\\cupleftarrow", "\\cupovercap", "\\cupvee", "\\curlyeqprec",
      "\\curlyeqsucc", "\\curlyvee", "\\curlywedge", "\\curvearrowleft",
      "\\curvearrowleftplus", "\\curvearrowright", "\\curvearrowrightminus",
      "\\cwcirclearrow", "\\cwgapcirclearrow", "\\cwopencirclearrow",
      "\\cwrightarcarrow", "\\cwundercurvearrow", "\\d", "\\dag", "\\dagger",
      "\\daleth", "\\danger", "\\dashcolon", "\\dashleftharpoondown",
      "\\dashrightharpoondown", "\\dashuline", "\\DashV", "\\Dashv", "\\dashV",
      "\\dashv", "\\DashVDash", "\\dashVdash", "\\dbkarrow", "\\ddag",
      "\\ddagger", "\\ddddot", "\\dddot", "\\ddot", "\\ddots", "\\ddotseq",
      "\\DDownarrow", "\\Ddownarrow", "\\def", "\\deg", "\\Delta", "\\delta",
      "\\det", "\\diameter", "\\Diamond", "\\diamond", "\\diamondbotblack",
      "\\diamondcdot", "\\diamondleftarrow", "\\diamondleftarrowbar",
      "\\diamondleftblack", "\\diamondrightblack", "\\diamondsuit",
      "\\diamondtopblack", "\\dicei", "\\diceii", "\\diceiii", "\\diceiv",
      "\\dicev", "\\dicevi", "\\dim", "\\dingasterisk", "\\disin",
      "\\disjquant", "\\div", "\\divideontimes", "\\divslash", "\\dot",
      "\\Doteq", "\\doteq", "\\dotequiv", "\\dotminus", "\\dotplus",
      "\\dotsim", "\\dotsminusdots", "\\dottedcircle", "\\dottedsquare",
      "\\dottimes", "\\dotuline", "\\doublebarvee", "\\doublebarwedge",
      "\\doubleplus", "\\Downarrow", "\\downarrow", "\\downarrowbar",
      "\\downarrowbarred", "\\downdasharrow", "\\downdownarrows",
      "\\downfishtail", "\\downharpoonleft", "\\downharpoonleftbar",
      "\\downharpoonright", "\\downharpoonrightbar", "\\downharpoonsleftright",
      "\\downrightcurvedarrow", "\\downtriangleleftblack",
      "\\downtrianglerightblack", "\\downuparrows",
      "\\downupharpoonsleftright", "\\downwhitearrow", "\\downzigzagarrow",
      "\\dprime", "\\draftingarrow", "\\drbkarrow", "\\droang", "\\dsol",
      "\\dsub", "\\dualmap", "\\egsdot", "\\eighthnote", "\\elinters", "\\ell",
      "\\elsdot", "\\em", "\\emph", "\\emptyset", "\\emptysetoarr",
      "\\emptysetoarrl", "\\emptysetobar", "\\emptysetocirc",
      "\\enclosecircle", "\\enclosediamond", "\\enclosesquare",
      "\\enclosetriangle", "\\end{center}", "\\end{description}",
      "\\end{document}", "\\end{enumerate}", "\\end{itemize}",
      "\\end{tabular}", "\\enleadertwodots", "\\enspace", "\\eparsl",
      "\\epsilon", "\\eqcirc", "\\eqcolon", "\\eqdef", "\\eqdot", "\\eqeq",
      "\\eqeqeq", "\\eqgtr", "\\eqless", "\\eqqgtr", "\\eqqless", "\\eqqplus",
      "\\eqqsim", "\\eqqslantgtr", "\\eqqslantless", "\\eqsim", "\\eqslantgtr",
      "\\eqslantless", "\\equal", "\\equalleftarrow", "\\equalparallel",
      "\\equalrightarrow", "\\Equiv", "\\equiv", "\\equivDD", "\\equivVert",
      "\\equivVvert", "\\eqvparsl", "\\errbarblackcircle",
      "\\errbarblackdiamond", "\\errbarblacksquare", "\\errbarcircle",
      "\\errbardiamond", "\\errbarsquare", "\\eta", "\\Eulerconst", "\\euro",
      "\\Exclam", "\\exists", "\\exp", "\\fallingdotseq", "\\fbowtie",
      "\\fcmp", "\\fdiagovnearrow", "\\fdiagovrdiag", "\\female", "\\fint",
      "\\Finv", "\\fisheye", "\\flat", "\\fltns", "\\footnotesize", "\\forall",
      "\\forks", "\\forksnot", "\\forkv", "\\fourthroot", "\\fourvdots",
      "\\frac", "\\fracslash", "\\frown", "\\fullouterjoin", "\\Game",
      "\\Gamma", "\\gamma", "\\gcd", "\\ge", "\\geq", "\\geqq", "\\geqqslant",
      "\\geqslant", "\\gescc", "\\gesdot", "\\gesdoto", "\\gesdotol",
      "\\gesles", "\\gets", "\\gg", "\\ggg", "\\gggnest", "\\gimel", "\\gla",
      "\\glE", "\\gleichstark", "\\glj", "\\gnapprox", "\\gneq", "\\gneqq",
      "\\gnsim", "\\grave", "\\greater", "\\gsime", "\\gsiml", "\\Gt", "\\gt",
      "\\gtcc", "\\gtcir", "\\gtlpar", "\\gtquest", "\\gtrapprox", "\\gtrarr",
      "\\gtrdot", "\\gtreqless", "\\gtreqqless", "\\gtrless", "\\gtrsim",
      "\\H", "\\harrowextender", "\\hat", "\\hatapprox", "\\hbar",
      "\\heartsuit", "\\Hermaphrodite", "\\hermitmatrix", "\\hexagon",
      "\\hexagonblack", "\\hknearrow", "\\hknwarrow", "\\hksearrow",
      "\\hkswarrow", "\\hline", "\\hom", "\\hookleftarrow", "\\hookrightarrow",
      "\\horizbar", "\\hourglass", "\\house", "\\hrectangle",
      "\\hrectangleblack", "\\href", "\\hslash", "\\Huge", "\\huge",
      "\\hyphenbullet", "\\hzigzag", "\\i", "\\iff", "\\iiiint", "\\iiint",
      "\\iinfin", "\\iint", "\\Im", "\\imageof", "\\imath", "\\implies",
      "\\in", "\\increment", "\\inf", "\\infty", "\\int", "\\intBar",
      "\\intbar", "\\intbottom", "\\intcap", "\\intclockwise", "\\intcup",
      "\\intercal", "\\interleave", "\\intextender", "\\intlarhk", "\\intprod",
      "\\intprodr", "\\inttop", "\\intx", "\\inversebullet",
      "\\inversewhitecircle", "\\invlazys", "\\invnot",
      "\\invwhitelowerhalfcircle", "\\invwhiteupperhalfcircle", "\\iota",
      "\\isindot", "\\isinE", "\\isinobar", "\\isins", "\\isinvb", "\\it",
      "\\item", "\\j", "\\jmath", "\\Join", "\\k", "\\kappa", "\\ker",
      "\\kernelcontraction", "\\Lambda", "\\lambda", "\\land", "\\lAngle",
      "\\langle", "\\langledot", "\\laplac", "\\LARGE", "\\Large", "\\large",
      "\\lat", "\\late", "\\LaTeX", "\\LaTeXe", "\\lbag", "\\lblkbrbrak",
      "\\lBrace", "\\lbrace", "\\lbracelend", "\\lbracemid", "\\lbraceuend",
      "\\lBrack", "\\lbrack", "\\lbrackextender", "\\lbracklend",
      "\\lbracklltick", "\\lbrackubar", "\\lbrackuend", "\\lbrackultick",
      "\\Lbrbrak", "\\lbrbrak", "\\lceil", "\\lcurvyangle", "\\ldots",
      "\\Ldsh", "\\le", "\\Leftarrow", "\\leftarrow", "\\leftarrowapprox",
      "\\leftarrowbackapprox", "\\leftarrowbsimilar", "\\leftarrowless",
      "\\leftarrowonoplus", "\\leftarrowplus", "\\leftarrowshortrightarrow",
      "\\leftarrowsimilar", "\\leftarrowsubset", "\\leftarrowtail",
      "\\leftarrowtriangle", "\\leftarrowx", "\\leftbkarrow",
      "\\leftcurvedarrow", "\\leftdasharrow", "\\leftdbkarrow",
      "\\leftdbltail", "\\leftdotarrow", "\\leftdowncurvedarrow",
      "\\leftfishtail", "\\leftharpoonaccent", "\\leftharpoondown",
      "\\leftharpoondownbar", "\\leftharpoonsupdown", "\\leftharpoonup",
      "\\leftharpoonupbar", "\\leftharpoonupdash", "\\leftleftarrows",
      "\\leftmoon", "\\leftouterjoin", "\\Leftrightarrow", "\\leftrightarrow",
      "\\leftrightarrowcircle", "\\leftrightarrows",
      "\\leftrightarrowtriangle", "\\leftrightharpoondowndown",
      "\\leftrightharpoondownup", "\\leftrightharpoons",
      "\\leftrightharpoonsdown", "\\leftrightharpoonsup",
      "\\leftrightharpoonupdown", "\\leftrightharpoonupup",
      "\\leftrightsquigarrow", "\\leftsquigarrow", "\\lefttail",
      "\\leftthreearrows", "\\leftthreetimes", "\\leftwavearrow",
      "\\leftwhitearrow", "\\leq", "\\leqq", "\\leqqslant", "\\leqslant",
      "\\lescc", "\\lesdot", "\\lesdoto", "\\lesdotor", "\\lesges", "\\less",
      "\\lessapprox", "\\lessdot", "\\lesseqgtr", "\\lesseqqgtr", "\\lessgtr",
      "\\lesssim", "\\lfbowtie", "\\lfloor", "\\lftimes", "\\lg",
      "\\lgblkcircle", "\\lgblksquare", "\\lgE", "\\lgroup", "\\lgwhtcircle",
      "\\lgwhtsquare", "\\lhd", "\\lim", "\\liminf", "\\limsup", "\\linefeed",
      "\\ll", "\\llangle", "\\llarc", "\\llblacktriangle", "\\llcorner",
      "\\LLeftarrow", "\\Lleftarrow", "\\lll", "\\lllnest", "\\llparenthesis",
      "\\lltriangle", "\\lmoustache", "\\ln", "\\lnapprox", "\\lneq",
      "\\lneqq", "\\lnot", "\\lnsim", "\\log", "\\longdashv", "\\longdivision",
      "\\Longleftarrow", "\\longleftarrow", "\\Longleftrightarrow",
      "\\longleftrightarrow", "\\longleftsquigarrow", "\\Longmapsfrom",
      "\\longmapsfrom", "\\Longmapsto", "\\longmapsto", "\\Longrightarrow",
      "\\longrightarrow", "\\longrightsquigarrow", "\\looparrowleft",
      "\\looparrowright", "\\lor", "\\lowint", "\\lozengeminus", "\\lParen",
      "\\lparen", "\\lparenextender", "\\Lparengtr", "\\lparenlend",
      "\\lparenless", "\\lparenuend", "\\lrarc", "\\lrblacktriangle",
      "\\lrcorner", "\\lrtriangle", "\\lrtriangleeq", "\\Lsh", "\\lsime",
      "\\lsimg", "\\lsqhook", "\\Lt", "\\lt", "\\ltcc", "\\ltcir", "\\ltimes",
      "\\ltlarr", "\\ltquest", "\\ltrivb", "\\lvboxline", "\\Lvzigzag",
      "\\lvzigzag", "\\male", "\\maltese", "\\mapsdown", "\\Mapsfrom",
      "\\mapsfrom", "\\Mapsto", "\\mapsto", "\\mapsup", "\\mathampersand",
      "\\mathatsign", "\\mathbb", "\\mathbf", "\\mathcal", "\\mathcolon",
      "\\mathcomma", "\\mathdollar", "\\matheth", "\\mathexclam", "\\mathfrak",
      "\\mathhyphen", "\\mathit", "\\mathoctothorpe", "\\mathparagraph",
      "\\mathpercent", "\\mathperiod", "\\mathplus", "\\mathquestion",
      "\\mathratio", "\\mathring", "\\mathsection", "\\mathsemicolon",
      "\\mathsf", "\\mathslash", "\\mathsterling", "\\mathtt",
      "\\mathvisiblespace", "\\mathyen", "\\max", "\\mbfDigamma",
      "\\mbfdigamma", "\\mbfeight", "\\mbffive", "\\mbffour", "\\mbfitnabla",
      "\\mbfitsansnabla", "\\mbfnabla", "\\mbfnine", "\\mbfone",
      "\\mbfsanseight", "\\mbfsansfive", "\\mbfsansfour", "\\mbfsansnabla",
      "\\mbfsansnine", "\\mbfsansone", "\\mbfsansseven", "\\mbfsanssix",
      "\\mbfsansthree", "\\mbfsanstwo", "\\mbfsanszero", "\\mbfseven",
      "\\mbfsix", "\\mbfthree", "\\mbftwo", "\\mbfzero", "\\mbox",
      "\\mdblkcircle", "\\mdblkdiamond", "\\mdblklozenge", "\\mdblksquare",
      "\\mdlgblkcircle", "\\mdlgblkdiamond", "\\mdlgblklozenge",
      "\\mdlgblksquare", "\\mdlgwhtcircle", "\\mdlgwhtdiamond",
      "\\mdlgwhtlozenge", "\\mdlgwhtsquare", "\\mdsmblkcircle",
      "\\mdsmblksquare", "\\mdsmwhtcircle", "\\mdsmwhtsquare", "\\mdwhtcircle",
      "\\mdwhtdiamond", "\\mdwhtlozenge", "\\mdwhtsquare", "\\measangledltosw",
      "\\measangledrtose", "\\measangleldtosw", "\\measanglelutonw",
      "\\measanglerdtose", "\\measanglerutone", "\\measangleultonw",
      "\\measangleurtone", "\\measeq", "\\measuredangle",
      "\\measuredangleleft", "\\measuredrightangle", "\\medblackstar",
      "\\medskip", "\\medwhitestar", "\\mfrakC", "\\mfrakH", "\\mfrakZ",
      "\\mho", "\\mid", "\\midbarvee", "\\midbarwedge", "\\midcir", "\\min",
      "\\minus", "\\minusdot", "\\minusfdots", "\\minusrdots", "\\mitBbbD",
      "\\mitBbbd", "\\mitBbbe", "\\mitBbbi", "\\mitBbbj", "\\mitnabla",
      "\\mlcp", "\\mod", "\\models", "\\modtwosum", "\\mp", "\\msanseight",
      "\\msansfive", "\\msansfour", "\\msansnine", "\\msansone",
      "\\msansseven", "\\msanssix", "\\msansthree", "\\msanstwo",
      "\\msanszero", "\\mscrB", "\\mscrE", "\\mscre", "\\mscrF", "\\mscrg",
      "\\mscrH", "\\mscrI", "\\mscrL", "\\mscrM", "\\mscro", "\\mscrR",
      "\\mtteight", "\\mttfive", "\\mttfour", "\\mttnine", "\\mttone",
      "\\mttseven", "\\mttsix", "\\mttthree", "\\mtttwo", "\\mttzero", "\\mu",
      "\\multimap", "\\multimapinv", "\\nabla", "\\napprox", "\\nasymp",
      "\\natural", "\\ncong", "\\ne", "\\Nearrow", "\\nearrow", "\\neg",
      "\\neovnwarrow", "\\neovsearrow", "\\neq", "\\nequiv", "\\neswarrow",
      "\\neuter", "\\newcommand", "\\newline", "\\newpage", "\\nexists",
      "\\ngeq", "\\ngtr", "\\ngtrless", "\\ngtrsim", "\\nHdownarrow",
      "\\nhpar", "\\nHuparrow", "\\nhVvert", "\\ni", "\\niobar", "\\nis",
      "\\nisd", "\\nLeftarrow", "\\nleftarrow", "\\nLeftrightarrow",
      "\\nleftrightarrow", "\\nleq", "\\nless", "\\nlessgtr", "\\nlesssim",
      "\\nmid", "\\nni", "\\normalsize", "\\Not", "\\not", "\\notin",
      "\\nparallel", "\\npolint", "\\nprec", "\\npreccurlyeq", "\\nRightarrow",
      "\\nrightarrow", "\\nsim", "\\nsime", "\\nsimeq", "\\nsqsubseteq",
      "\\nsqsupseteq", "\\nsubset", "\\nsubseteq", "\\nsucc", "\\nsucccurlyeq",
      "\\nsupset", "\\nsupseteq", "\\ntrianglelefteq", "\\ntrianglerighteq",
      "\\nu", "\\nvartriangleleft", "\\nvartriangleright", "\\nVDash",
      "\\nVdash", "\\nvDash", "\\nvdash", "\\nvinfty", "\\nVleftarrow",
      "\\nvLeftarrow", "\\nvleftarrow", "\\nVleftarrowtail",
      "\\nvleftarrowtail", "\\nVleftrightarrow", "\\nvLeftrightarrow",
      "\\nvleftrightarrow", "\\nVrightarrow", "\\nvRightarrow",
      "\\nvrightarrow", "\\nVrightarrowtail", "\\nvrightarrowtail",
      "\\nVtwoheadleftarrow", "\\nvtwoheadleftarrow",
      "\\nVtwoheadleftarrowtail", "\\nvtwoheadleftarrowtail",
      "\\nVtwoheadrightarrow", "\\nvtwoheadrightarrow",
      "\\nVtwoheadrightarrowtail", "\\nvtwoheadrightarrowtail", "\\Nwarrow",
      "\\nwarrow", "\\nwovnearrow", "\\nwsearrow", "\\obar", "\\obot",
      "\\obrbrak", "\\obslash", "\\ocirc", "\\ocommatopright", "\\odiv",
      "\\odot", "\\odotslashdot", "\\ogreaterthan", "\\oiiint", "\\oiint",
      "\\oint", "\\ointctrclockwise", "\\olcross", "\\olessthan", "\\Omega",
      "\\omega", "\\omicron", "\\ominus", "\\operp", "\\oplus", "\\opluslhrim",
      "\\oplusrhrim", "\\origof", "\\oslash", "\\Otimes", "\\otimes",
      "\\otimeshat", "\\otimeslhrim", "\\otimesrhrim", "\\oturnedcomma",
      "\\overbar", "\\overline", "\\ovhook", "\\owns", "\\par", "\\paragraph",
      "\\parallel", "\\parallelogram", "\\parallelogramblack", "\\parsim",
      "\\partial", "\\partialmeetcontraction", "\\pentagon", "\\pentagonblack",
      "\\perp", "\\perps", "\\Phi", "\\phi", "\\Pi", "\\pi", "\\pitchfork",
      "\\Planckconst", "\\plusdot", "\\pluseqq", "\\plushat", "\\plussim",
      "\\plussubtwo", "\\plustrif", "\\pm", "\\pointint", "\\postalmark",
      "\\Pr", "\\Prec", "\\prec", "\\precapprox", "\\preccurlyeq", "\\preceq",
      "\\preceqq", "\\precnapprox", "\\precneq", "\\precneqq", "\\precnsim",
      "\\precsim", "\\prime", "\\prod", "\\profline", "\\profsurf",
      "\\PropertyLine", "\\propto", "\\prurel", "\\Psi", "\\psi", "\\pullback",
      "\\pushout", "\\QED", "\\qprime", "\\qquad", "\\quad", "\\quarternote",
      "\\questeq", "\\Question", "\\r", "\\rAngle", "\\rangle", "\\rangledot",
      "\\rangledownzigzagarrow", "\\rbag", "\\rblkbrbrak", "\\rBrace",
      "\\rbrace", "\\rbracelend", "\\rbracemid", "\\rbraceuend", "\\rBrack",
      "\\rbrack", "\\rbrackextender", "\\rbracklend", "\\rbracklrtick",
      "\\rbrackubar", "\\rbrackuend", "\\rbrackurtick", "\\Rbrbrak",
      "\\rbrbrak", "\\rceil", "\\rcurvyangle", "\\rdiagovfdiag",
      "\\rdiagovsearrow", "\\Rdsh", "\\Re", "\\renewcommand", "\\revangle",
      "\\revangleubar", "\\revemptyset", "\\revnmid", "\\rfbowtie", "\\rfloor",
      "\\rftimes", "\\rgroup", "\\rhd", "\\rho", "\\rightangle",
      "\\rightanglemdot", "\\rightanglesqr", "\\Rightarrow", "\\rightarrow",
      "\\rightarrowapprox", "\\rightarrowbackapprox", "\\rightarrowbar",
      "\\rightarrowbsimilar", "\\rightarrowdiamond", "\\rightarrowgtr",
      "\\rightarrowonoplus", "\\rightarrowplus", "\\rightarrowshortleftarrow",
      "\\rightarrowsimilar", "\\rightarrowsupset", "\\rightarrowtail",
      "\\rightarrowtriangle", "\\rightarrowx", "\\rightbkarrow",
      "\\rightcurvedarrow", "\\rightdasharrow", "\\rightdbltail",
      "\\rightdotarrow", "\\rightdowncurvedarrow", "\\rightfishtail",
      "\\rightharpoonaccent", "\\rightharpoondown", "\\rightharpoondownbar",
      "\\rightharpoonsupdown", "\\rightharpoonup", "\\rightharpoonupbar",
      "\\rightharpoonupdash", "\\rightimply", "\\rightleftarrows",
      "\\rightleftharpoons", "\\rightleftharpoonsdown",
      "\\rightleftharpoonsup", "\\rightmoon", "\\rightouterjoin",
      "\\rightpentagon", "\\rightpentagonblack", "\\rightrightarrows",
      "\\rightsquigarrow", "\\righttail", "\\rightthreearrows",
      "\\rightthreetimes", "\\rightwavearrow", "\\rightwhitearrow",
      "\\ringplus", "\\risingdotseq", "\\rmoustache", "\\rParen", "\\rparen",
      "\\rparenextender", "\\rparengtr", "\\rparenlend", "\\Rparenless",
      "\\rparenuend", "\\rppolint", "\\rrangle", "\\RRightarrow",
      "\\Rrightarrow", "\\rrparenthesis", "\\Rsh", "\\rsolbar", "\\rsqhook",
      "\\rsub", "\\rtimes", "\\rtriltri", "\\ruledelayed", "\\rvboxline",
      "\\Rvzigzag", "\\rvzigzag", "\\sansLmirrored", "\\sansLturned", "\\sc",
      "\\scpolint", "\\scriptsize", "\\scurel", "\\Searrow", "\\searrow",
      "\\sec", "\\section", "\\seovnearrow", "\\setminus", "\\sf", "\\sharp",
      "\\shortdowntack", "\\shortlefttack", "\\shortrightarrowleftarrow",
      "\\shortuptack", "\\shuffle", "\\Sigma", "\\sigma", "\\sim", "\\sime",
      "\\simeq", "\\simgE", "\\simgtr", "\\similarleftarrow",
      "\\similarrightarrow", "\\simlE", "\\simless", "\\simminussim",
      "\\simneqq", "\\simplus", "\\simrdots", "\\sin", "\\sinewave", "\\sinh",
      "\\small", "\\smallblacktriangleleft", "\\smallblacktriangleright",
      "\\smallin", "\\smallni", "\\smallsetminus", "\\smallskip",
      "\\smalltriangleleft", "\\smalltriangleright", "\\smashtimes",
      "\\smblkcircle", "\\smblkdiamond", "\\smblklozenge", "\\smblksquare",
      "\\smeparsl", "\\smile", "\\smt", "\\smte", "\\smwhitestar",
      "\\smwhtcircle", "\\smwhtdiamond", "\\smwhtlozenge", "\\smwhtsquare",
      "\\sout", "\\spadesuit", "\\sphericalangle", "\\sphericalangleup",
      "\\Sqcap", "\\sqcap", "\\Sqcup", "\\sqcup", "\\sqint", "\\sqlozenge",
      "\\sqrt", "\\sqrtbottom", "\\sqsubset", "\\sqsubseteq", "\\sqsubsetneq",
      "\\sqsupset", "\\sqsupseteq", "\\sqsupsetneq", "\\square",
      "\\squarebotblack", "\\squarecrossfill", "\\squarehfill",
      "\\squarehvfill", "\\squareleftblack", "\\squarellblack",
      "\\squarellquad", "\\squarelrblack", "\\squarelrquad",
      "\\squareneswfill", "\\squarenwsefill", "\\squarerightblack",
      "\\squaretopblack", "\\squareulblack", "\\squareulquad",
      "\\squareurblack", "\\squareurquad", "\\squarevfill", "\\squoval",
      "\\sslash", "\\star", "\\stareq", "\\strns", "\\subedot", "\\submult",
      "\\subrarr", "\\subsection", "\\Subset", "\\subset", "\\subsetapprox",
      "\\subsetcirc", "\\subsetdot", "\\subseteq", "\\subseteqq",
      "\\subsetneq", "\\subsetneqq", "\\subsetplus", "\\subsim", "\\subsub",
      "\\subsubsection", "\\subsup", "\\Succ", "\\succ", "\\succapprox",
      "\\succcurlyeq", "\\succeq", "\\succeqq", "\\succnapprox", "\\succneq",
      "\\succneqq", "\\succnsim", "\\succsim", "\\sum", "\\sumbottom",
      "\\sumint", "\\sumtop", "\\sun", "\\sup", "\\supdsub", "\\supedot",
      "\\suphsol", "\\suphsub", "\\suplarr", "\\supmult", "\\Supset",
      "\\supset", "\\supsetapprox", "\\supsetcirc", "\\supsetdot",
      "\\supseteq", "\\supseteqq", "\\supsetneq", "\\supsetneqq",
      "\\supsetplus", "\\supsim", "\\supsub", "\\supsup", "\\surd",
      "\\Swarrow", "\\swarrow", "\\talloblong", "\\tan", "\\tanh", "\\tau",
      "\\text", "\\textAlpha", "\\textalpha", "\\textBeta", "\\textbeta",
      "\\textbf", "\\textChi", "\\textchi", "\\textcopyright", "\\textDelta",
      "\\textdelta", "\\textEpsilon", "\\textepsilon", "\\textEta",
      "\\texteta", "\\textGamma", "\\textgamma", "\\textIota", "\\textiota",
      "\\textit", "\\textKappa", "\\textkappa", "\\textLambda", "\\textlambda",
      "\\textMu", "\\textmu", "\\textNu", "\\textnu", "\\textOmega",
      "\\textomega", "\\textOmikron", "\\textomikron", "\\textPhi",
      "\\textphi", "\\textPi", "\\textpi", "\\textPsi", "\\textpsi",
      "\\textregistered", "\\textRho", "\\textrho", "\\textsc", "\\textsf",
      "\\textSigma", "\\textsigma", "\\textTau", "\\texttau", "\\textTheta",
      "\\texttheta", "\\texttrademark", "\\texttt", "\\textUpsilon",
      "\\textupsilon", "\\textXi", "\\textxi", "\\textZeta", "\\textzeta",
      "\\therefore", "\\thermod", "\\Theta", "\\theta", "\\threedangle",
      "\\threedotcolon", "\\threeunderdot", "\\tieconcat", "\\tieinfty",
      "\\tilde", "\\times", "\\timesbar", "\\tiny", "\\tminus", "\\to",
      "\\toea", "\\tona", "\\top", "\\topbot", "\\topcir", "\\topfork",
      "\\topsemicircle", "\\tosa", "\\towa", "\\tplus", "\\trapezium",
      "\\triangle", "\\trianglecdot", "\\triangledown", "\\triangleleft",
      "\\triangleleftblack", "\\trianglelefteq", "\\triangleminus",
      "\\triangleodot", "\\triangleplus", "\\triangleq", "\\triangleright",
      "\\trianglerightblack", "\\trianglerighteq", "\\triangles",
      "\\triangleserifs", "\\triangletimes", "\\triangleubar", "\\tripleplus",
      "\\trprime", "\\trslash", "\\tt", "\\turnangle", "\\turnediota",
      "\\turnednot", "\\twocaps", "\\twocups", "\\twoheaddownarrow",
      "\\twoheadleftarrow", "\\twoheadleftarrowtail", "\\twoheadleftdbkarrow",
      "\\twoheadmapsfrom", "\\twoheadmapsto", "\\twoheadrightarrow",
      "\\twoheadrightarrowtail", "\\twoheaduparrow", "\\twoheaduparrowcircle",
      "\\twolowline", "\\twonotes", "\\typecolon", "\\u", "\\ubrbrak",
      "\\ularc", "\\ulblacktriangle", "\\ulcorner", "\\uline", "\\ultriangle",
      "\\uminus", "\\underline", "\\unicodecdots", "\\unicodeellipsis",
      "\\unlhd", "\\unrhd", "\\upand", "\\Uparrow", "\\uparrow",
      "\\uparrowbarred", "\\uparrowoncircle", "\\upbackepsilon",
      "\\updasharrow", "\\Updownarrow", "\\updownarrow", "\\updownarrowbar",
      "\\updownarrows", "\\updownharpoonleftleft", "\\updownharpoonleftright",
      "\\updownharpoonrightleft", "\\updownharpoonrightright",
      "\\updownharpoonsleftright", "\\upfishtail", "\\upharpoonleft",
      "\\upharpoonleftbar", "\\upharpoonright", "\\upharpoonrightbar",
      "\\upharpoonsleftright", "\\upin", "\\upint", "\\uplus",
      "\\uprightcurvearrow", "\\Upsilon", "\\upsilon", "\\upuparrows",
      "\\upwhitearrow", "\\urarc", "\\urblacktriangle", "\\urcorner", "\\url",
      "\\urtriangle", "\\uuline", "\\UUparrow", "\\Uuparrow", "\\v",
      "\\varbarwedge", "\\varcarriagereturn", "\\varclubsuit",
      "\\vardiamondsuit", "\\vardoublebarwedge", "\\varepsilon",
      "\\varheartsuit", "\\varhexagon", "\\varhexagonblack",
      "\\varhexagonlrbonds", "\\varisinobar", "\\varisins", "\\varkappa",
      "\\varlrtriangle", "\\varniobar", "\\varnis", "\\varnothing",
      "\\varointclockwise", "\\varphi", "\\varpi", "\\varrho", "\\varsigma",
      "\\varspadesuit", "\\varstar", "\\varTheta", "\\vartheta",
      "\\vartriangle", "\\vartriangleleft", "\\vartriangleright", "\\varVdash",
      "\\varveebar", "\\Vbar", "\\vBar", "\\vBarv", "\\vbraceextender",
      "\\vbrtri", "\\VDash", "\\Vdash", "\\vDash", "\\vdash", "\\vDdash",
      "\\vdots", "\\vec", "\\vectimes", "\\Vee", "\\vee", "\\veebar",
      "\\veedot", "\\veedoublebar", "\\veeeq", "\\veemidvert", "\\veeodot",
      "\\veeonvee", "\\veeonwedge", "\\verb", "\\Vert", "\\vert",
      "\\vertoverlay", "\\viewdata", "\\vlongdash", "\\vrectangle",
      "\\vrectangleblack", "\\Vvdash", "\\Vvert", "\\vysmblkcircle",
      "\\vysmblksquare", "\\vysmwhtcircle", "\\vysmwhtsquare", "\\vzigzag",
      "\\Wedge", "\\wedge", "\\wedgebar", "\\wedgedot", "\\wedgedoublebar",
      "\\wedgemidvert", "\\wedgeodot", "\\wedgeonwedge", "\\wedgeq",
      "\\whitearrowupfrombar", "\\whiteinwhitetriangle", "\\whitepointerleft",
      "\\whitepointerright", "\\whitesquaretickleft", "\\whitesquaretickright",
      "\\whthorzoval", "\\whtvertoval", "\\wideangledown", "\\wideangleup",
      "\\widebridgeabove", "\\wp", "\\wr", "\\xbsol", "\\Xi", "\\xi", "\\xsol",
      "\\Yup", "\\Zbar", "\\zcmp", "\\zeta", "\\zpipe", "\\zproject"];
    function hinting(editor, options) {
      var cur = editor.getCursor();
      var token = editor.getTokenAt(cur);
      var completions = [];
      if (!/^\\[A-Za-z_]*$/.test(token.string)) {
        if (options.force_completion && token.className !== "comment") {
          for (var i = 0, e = keywords.length; i < e; ++i)
            completions.push(token.string+keywords[i]);
        } else
          return;
      } else {
        for (var i = 0, e = keywords.length; i < e; ++i) {
          if (keywords[i].lastIndexOf(token.string, 0) === 0)
            completions.push(keywords[i]);
        }
      }
      return {
        list: completions,
        from: CodeMirror.Pos(cur.line, token.start),
        to: CodeMirror.Pos(cur.line, token.end)
      };
    }
    function autocomplete(cm) {
      CodeMirror.showHint(cm, hinting, {completeSingle: false, force_completion: true});
    }
    function autocomplete_backslash(cm) {
      setTimeout(function() {
        if (!cm.state.completionActive)
          CodeMirror.showHint(cm, hinting, {completeSingle: false, force_completion: false});
      }, 100);
      return CodeMirror.Pass;
    }
    return {
      "'\\'": autocomplete_backslash,
      "Ctrl-Space": autocomplete,
    };
  }
  var mode = CodeMirror.mimeModes["text/x-latex"];
  if (typeof mode == "string")
    mode = CodeMirror.mimeModes["text/x-latex"] = {name: mode};
  mode.autocompleteHinting = latex_autocomplete();
}());
